# Generated by Django 2.1.4 on 2018-12-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
