# Generated by Django 2.1.4 on 2018-12-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0002_auto_20181217_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
