# Generated by Django 2.1.4 on 2018-12-17 10:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0003_auto_20181217_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='children', to='site_persons.Human', verbose_name='Начальник'),
        ),
    ]
