# Generated by Django 2.1.4 on 2018-12-17 15:31

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0005_auto_20181217_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='site_persons.Human', verbose_name='Начальник'),
        ),
    ]
