# Generated by Django 2.1.4 on 2018-12-17 19:47

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0006_auto_20181217_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
    ]
