# Generated by Django 2.1.4 on 2018-12-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0007_human_search_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='search_index',
        ),
    ]
