# Generated by Django 2.1.4 on 2018-12-17 20:41

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_persons', '0008_remove_human_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
    ]
